spring:
  profiles:
    group:
      liveload:
        - local
        - moex-default
        - loadall

---
spring:
  config:
    activate:
      on-profile: local

app:
  loader:
    storage-dir: C:/dev/moex-data/data
    delayBetweenEmitentLoadMs: 1000
    delayBetweenMoexRequestsMs: 100

---
spring:
  config:
    activate:
      on-profile: moex-default

moex:
  api:
    securities:
      base-url: https://iss.moex.com/iss/engines/stock/markets/shares/securities/
      trades:
        sub-url: /trades.xml
        page-size: 5000
        max-page-num: 1000
        emitent-codes:
          - GAZP
          - VTBR
          - MRKP
          - CHMF
          - SIBN
          - ROSN
          - SBER
          - FLOT
          - ENRU
          - BANEP
          - TATNP
          - PHOR
          - TRMK
          - MAGN
          - AFKS
          - AFLT
          - ALRS
          - AQUA
          - CBOM
          - DSKY
          - FEES
          - FIVE
          - GMKN
          - HYDR
          - IRAO
          - LKOH
          - LNTA
          - LSRG
          - MGNT
          - MOEX
          - MTSS
          - NLMK
          - NVTK
          - PIKK
          - PLZL
          - POLY
          - RTKM
          - RUAL
          - SBERP
          - SNGS
          - SNGSP
          - TATN
          - TCSG
          - TRNFP
          - UPRO
          - YNDX
          - BANE
          - VSMO
          - MSRS
          - RASP
